package templates

var IndexTemplate string = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tartalomjegyzék</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        html, body {
            font-family: serif;
        }

        #copyright, #source, #credentials {
            border-top: 1px solid black;
        }
    </style>
</head>
<body class="text-white bg-dark">
<header class="container text-center">
    <h1>
        Online Pentacon Múzeum<br>
        <small>Online Pentacon Museum</small>
    </h1>
</header>

<main class="container">
    <h1>Tartalomjegyzék</h1>
    <ol>
        {{ range $id, $name := . }}
            <li><a href="{{ $id }}.html" class="text-info">{{ $name }}</a></li>
        {{ end }}
    </ol>
</main>

<footer class="container small">
    <div class="row" id="copyright">
        <div class="col">
            <p>A felvételek és az oldal tartalma az Online Pentacon Múzeum, illetve az adatokkal rendelkezni jogosult
                források tulajdonát képezik.</p>
            <p>Digitalizálta: Interspect Kft.</p>
        </div>
    </div>

    <div class="row" id="source">
        <div class="col">
            <p>Az adatok forrásai:</p>
            <ul>
                <li>A Hungarian Pentacon Museum tárgyjegyzéke</li>
                <li>http://www.praktica-collector.de (Dr. Mike Otto adatbázisa)
                <li>Roger Rossing 1969: The Praktica Book p. 256.
                <li>Roger Rössing 1965, 1986: Fotografie mit der Praktica
                <li>Leonard Gaunt 1972: The Praktica way
                <li>Roger Rössing, Morvay György, Dr. Sevcsik Jenő 1979: Fényképezés Prakticával</li>
                <li>Gerhard Jehmlich 2009: A VEB Pentacon Drezda. A Drezda kamera és mozi ipar története 1945 után,
                    Drezda
                </li>
                <li>Barry M. Jones. Publisher, Barry M Jones, 2014: From KW to Pentacon: The Story of Kamera
                    Werkstätten, Praktica and Pentacon Cameras
                </li>
            </ul>
        </div>
    </div>

    <div class="row" id="credentials">
        <div class="col text-center">
            Generated by <a href="https://github.com/kergeodeta/pentaconmuseum" class="text-info">PentaconMuseum</a> | Written in <a
                    href="https://golang.org/" class="text-info">Go</a> | Developed by <a
                    href="https://github.com/kergeodeta" class="text-info">kergeodeta</a>
        </div>
    </div>
</footer>

</body>
</html>
`